class QuranData{


 static var list = [
   "Al-Fatihah (The Opening)",
    "Al-Baqarah (The Cow)",
    "Aali Imran (The Family of Imran)",
    "An-Nisa' (The Women)",
    "Al-Ma'idah (The Table Spread)",
    "Al-An'am (The Cattle)",
    "Al-A'raf (The Heights)",
    "Al-Anfal (The Spoils of War)",
    "At-Tawbah (The Repentance)",
    "Yunus (Jonah)",
    "Hud (Hud)",
    "Yusuf (Joseph)",
    "Ar-Rad (The Thunder)",
    "Ibrahim (Abraham)",
    "Al-Hijr (The Rocky Tract)",
    "An-Nahl (The Bee)",
    "Al-Isra (The Night Journey)",
    "Al-Kahf (The Cave)",
    "Maryam (Mary)",
    "Ta-Ha (Ta-Ha)",
    "Al-Anbiya (The Prophets)",
    "Al-Hajj (The Pilgrimage)",
    "Al-Mu'minun (The Believers)",
    "An-Nur (The Light)",
    "Al-Furqan (The Criterion)",
    "Ash-Shu'ara (The Poets)",
    "An-Naml (The Ant)",
    "Al-Qasas (The Stories)",
    "Al-Ankabut (The Spider)",
    "Ar-Rum (The Romans)",
    "Luqman (Luqman)",
    "As-Sajdah (The Prostration)",
    "Al-Ahzab (The Combined Forces)",
    "Saba (Sheba)",
    "Fatir (The Originator)",
    "Ya-Sin (Ya-Sin)",
    "As-Saffat (Those who set the Ranks)",
    "Sad (The Letter Sad)",
    "Az-Zumar (The Troops)",
    "Ghafir (The Forgiver)",
    "Fussilat (Explained in Detail)",
    "Ash-Shura (The Consultation)",
    "Az-Zukhruf (The Gold Adornments)",
    "Ad-Dukhan (The Smoke)",
    "Al-Jathiya (The Crouching)",
    "Al-Ahqaf (The Wind-Curved Sandhills)",
    "Muhammad (Muhammad)",
    "Al-Fath (The Victory)",
    "Al-Hujurat (The Rooms)",
    "Qaf (The Letter Qaf)",
    "Adh-Dhariyat (The Winnowing Winds)",
    "At-Tur (The Mount)",
    "An-Najm (The Star)",
    "Al-Qamar (The Moon)",
    "Ar-Rahman (The Beneficent)",
    "Al-Waqi'a (The Inevitable)",
    "Al-Hadid (The Iron)",
    "Al-Mujadila (The Pleading Woman)",
    "Al-Hashr (The Exile)",
    "Al-Mumtahina (She that is to be examined)",
    "As-Saff (The Ranks)",
    "Al-Jumu'a (The Congregation)",
    "Al-Munafiqun (The Hypocrites)",
    "At-Taghabun (The Mutual Disillusion)",
    "At-Talaq (The Divorce)",
    "At-Tahrim (The Prohibition)",
    "Al-Mulk (The Sovereignty)",
    "Al-Qalam (The Pen)",
    "Al-Haaqqa (The Reality)",
    "Al-Ma'",
    "Al-Ma'arij (The Ascending Stairways)",
    "Nuh (Noah)",
    "Al-Jinn (The Jinn)",
    "Al-Muzzammil (The Enshrouded One)",
    "Al-Muddathir (The Cloaked One)",
    "Al-Qiyamah (The Resurrection)",
    "Al-Insan (Man)",
    "Al-Mursalat (The Emissaries)",
    "An-Naba (The Tidings)",
    "An-Nazi'at (Those who drag forth)",
    "'Abasa (He frowned)",
    "At-Takwir (The Overthrowing)",
    "Al-Infitar (The Cleaving)",
    "Al-Mutaffifin (Defrauding)",
    "Al-Inshiqaq (Splitting Open)",
    "Al-Burooj (The Mansions of the Stars)",
    "At-Tariq (The Morning Star)",
    "Al-Ala (The Most High)",
    "Al-Ghashiya (The Overwhelming)",
    "Al-Fajr (The Dawn)",
    "Al-Balad (The City)",
    "Ash-Shams (The Sun)",
    "Al-Lail (The Night)",
    "Ad-Dhuha (The Morning Hours)",
    "Ash-Sharh (The Relief)",
    "At-Tin (The Fig)",
    "Al-'Alaq (The Clot)",
    "Al-Qadr (The Power)",
    "Al-Bayyina (The Clear Proof)",
    "Az-Zalzala (The Earthquake)",
    "Al-'Adiyat (The Courser)",
    "Al-Qari'a (The Calamity)",
    "At-Takathur (The Rivalry in world increase)",
    "Al-'Asr (The Declining Day)",
    "Al-Humaza (The Traducer)",
    "Al-Fil (The Elephant)",
    "Quraysh (Quraysh)",
    "Al-Ma'un (Small Kindnesses)",
    "Al-Kawthar (Abundance)",
    "Al-Kafiroon (The Disbelievers)",
    "An-Nasr (Divine Support)",
    "Al-Masad (The Palm Fiber)",
    "Al-Ikhlas (The Sincerity)"
    "Al-Falaq (The Daybreak)"
    "An-Nas (Mankind)"
  ];


}